
version: '4'
 services:
   cryptoinvestor-service:
     build: ./cryptoinvestor
     volume:
       - cryptoinvestor:/usr/bin/cryptoinvestor/_server/server.js

         name: cryptoinvestor
         port: 4000:4000


